### ISSUE TITLE
vizier query

### ISSUE THREAD

**Issue by biqingfor** [askap-qc/validation#7]
argparse option to use vizier query or to use a local copy of HIPASS catalog.

**Comment by mattwhiting** [comment]
FYI, I found that increasing the timeout in the Vizier query allowed it to run without failure in a slurm job on galaxy. See pull request.
Having this optional would potentially be useful, if you did want to run without requiring that network load.

**Comment by biqingfor** [comment]
I have decided to use the mirror site as it seems to be up more often than the server in Strasbourg. See the pull request.
